spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
#    defer-datasource-initialization: true
#    show-sql: true System.out.println()

  # multipart 사이즈 설정
  servlet:
    multipart:
      max-request-size: 1024MB
      max-file-size: 1024MB

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

# S3 Bucket
cloud:
  aws:
    credentials:
      access-key:
      secret-key:
    stack:
      auto: false
    region:
      static: ap-northeast-2
    s3:
      bucket: coldrain-f-bucket
